### ISSUE TITLE
Version 1.2.0 is not backward compatible with 1.1.0

### ISSUE THREAD

**Issue by DroopyTersen** [rannn505/node-powershell#10]
Latest bits look great, but probably qualify as a semver major release?

Usage that broke with 1.2.0
var PowerShell = require("node-powershell");
var psCommand = new PowerShell(scriptBlock);

Node is defaulting to ^ (caret) now so I had modules breaking after doing a simple npm update.

**Comment by rannn505** [comment]
Hey @DroopyTersen 
I am very sorry to hear about the problem I created for you, you are absolutely right and I'll take it to my attention next time.
(I was reading how to manage the whole thing with the semver because of you .. so thx :+1: )
Finally, I was glad to hear you liked the last commit, And I'd love to hear what you think about the new one I released yesterday. sorry again :)
