### ISSUE TITLE
Synchronous Invokation

### ISSUE THREAD

**Issue by cawoodm** [rannn505/node-powershell#14]
I know it goes against node's grain but is there any way to invoke the PS commands synchronously?

**Comment by rannn505** [comment]
Hey @cawoodm ,
First of all sorry it took me a long time to answer. 💯
Second of all, what do you mean when you say synchronously?
Basically, PS invoke most of his commands synchronously:
> PowerShell is a task automation and configuration management framework from Microsoft, consisting of a command-line shell and associated scripting language built on the **.NET Framework.** [wikipedia](https://en.wikipedia.org/wiki/PowerShell)

Let me know if you need further help ... maybe you can add an example... 
GL and THx :+1:

**Comment by alexkokkinos** [comment]
@rannn505 
I realize this is a really old issue that's been closed, but I thought I'd clarify what @cawoodm meant since he/she didn't clarify, and I was working on something tangentially related that brought me here:

PowerShell invokes most commands synchronously, but the node-powershell Invoke function is asynchronous, so if one wants to wait for their PowerShell command to finish before moving on to the next line of their Node script they will of course have to call a function from the promise resolution or use async/await.

Since Powershell is generally synchronous, I think @cawoodm is making the request that node-powershell also have a synchronous function to invoke the PowerShell commands so that promises are not returned by node-powershell's Invoke function.

Essentially, the ask is about the possibility of creating a Sync option similarly to how projects like fs-extra or klaw/klaw-sync work.

With the convenience of async/await and all the design norms of node, I'm not sure this feature would be so helpful, but that's what @cawoodm was inquiring about.

**Comment by BenjaminMichael** [comment]
I achieved sync'ing up my node-powershell promises by wrapping them in a recursive function that you call inside the then() block of the promise until you've finished all the promises.

Dont forget to .dispose() unless you want a lot of PS consoles open in memory ;)

**Comment by BenjaminMichael** [comment]
made a demo here:
https://github.com/BenjaminMichael/node-powershell-electron-basic-demo

here's an excerpt:
```javascript
// promises in sequence

        function rapidFirePromise(i){
            let ps = new shell({
                executionPolicy: 'Bypass',
                noProfile: true
                });
                
                ps.addCommand(`$x=$PSVersionTable;write-host '${i+1}: idunno. ${testData[i]}'`)
                ps.invoke()
                .then(output => {
                ps.dispose()
                doneLoading(output)
                if (i<max-1){i++;return rapidFirePromise(i)}
                })

                .catch(err => {
                    errorUIFeedback()
                    console.log(err)
                    ps.dispose()
                });
             }
        rapidFirePromise(0)
```
