### ISSUE TITLE
Issue with ps dispose

### ISSUE THREAD

**Issue by gopikishanm** [rannn505/node-powershell#37]
Hi,

I am trying to use the library to invoke ps and then return to callback function. If I include ps.dispose in my code, the callback is never called. Below find my code snippet below

![image](https://user-images.githubusercontent.com/20774988/32396042-dc924f32-c137-11e7-8842-fd751723b95a.png)

Can you please tell me when I should call ps.dispose in this case. Should it be before callback function or after that

Thanks
Gopi

**Comment by BenjaminMichael** [comment]
It should go inside the catch block.  There is an example in the readme along with a link to the API documentation.

**Comment by BenjaminMichael** [comment]
shellName.dispose() frees up the powershell console resources and so you want to do this when you catch any error but I also use it in the then() block to free up resources once Im finished with a PS console.  NOTE: if you dispose() but your .ps1 script hasnt completed due to a bug you will get a powershell error from the command "exitexit" being entered

**Comment by xanaxx** [comment]
Hi. I see you are using it with VM's 🙏
The solution which I have uses promise and you do not have to worry about `Shell` object.

```js
const powershell= new Shell();

return new Promise(resolve => {
        powershell.invoke().then(result => {
            resolve(result);
        }).then(() => {
            powershell.dispose();
        }).catch(() => {
            powershell.dispose();
        });
    });
```
