### ISSUE TITLE
Cannot run import-csv argv

### ISSUE THREAD

**Issue by serganus** [rannn505/node-powershell#4]
I was trying to use this : 
``` powershell.exe import-csv file.txt -Delimiter "`t"> file.csv```

It works fine when pasted into console but fails saying "Missing an argument for parameter "Delimiter"".

I think some issue when the node process converts argv on console. Please help!

**Comment by rannn505** [comment]
Hey @serganus ,
Sorry for the long waiting, I was pretty busy lately.
So... I ran  a little test, In an attempt to reproduce the issue that you raised:
`test.js`
```javascript
PS = new shell('Get-Content -Delimiter "`t" file.txt > file.csv ');
```
`file.txt`
issue4 (tab) issue4 (tab) issue4
And Script finished successfully (0).

The way I see it, you have several options:
- Check your quotes (pay attention when you use single or double).
- Try using Get-Content instead of import-csv
- Try saving your commands as a .ps1 script and use it like this:
```javascript
PS = new shell("Path/To/Your/Script.ps1");
```

Let me know if you managed to solved this, or you need further help .. 
I'd love you to add a star to the project :)
THx :+1:
