### ISSUE TITLE
Can I supress errors or warnings?

### ISSUE THREAD

**Issue by dhuber666** [rannn505/node-powershell#52]
Hi,
I run a powershell script that has to import a pssession first (to get access to the `Add-MailboxPermission` Command). 
It does import it but it also returns a little warning:

> Warning: The names of a few imported commands on modul "tmp_4wm2ycxh.e5r" contains not approved verbs....

So I don't care about the warning but then the script cancels out into the "error" function and doesn't get to the actual `Add-MailboxPermission` command. 

How can I solve this problem? 
Great Project btw.!

**Comment by BenjaminMichael** [comment]
You can disable that warning when you call Import-Module by using the -DisableNameChecking switch.

**Comment by BenjaminMichael** [comment]
Here is another example of an error you could suppress or not suppress errors.  The basic idea is you get error data from a try/catch and pass it back in a JSON string.

the powershell:
https://github.com/BenjaminMichael/Node-Powershell-Electron-Intermediate-Demo/blob/master/scripts/get-ADUser.ps1

and instead of using a "then" statement in this example I am using the .on output event listener:

```
ps.on('output', output =>{
    let data = JSON.parse(output);
    console.log("PowerShell returning data: " + output);
    evaluatePSOutput(data);
});

```
here is whre the error handling happens (or if no error, do other stuff)



```
const evaluatePSOutput = (data) => {
    switch(data[0].Result){
        case "Get-ADUser Remove Error":
            DOM.resetMyRemoveForm(); //error occurred, reset form
            $('#redMessageBar').html(data[0].Error.Message); //report the error to DOM or you could not
            return;
        break;

//do other stuff ...

```

**Comment by dhuber666** [comment]
Thank you @BenjaminMichael I understand it now 👍 
Good point with your second example.
