### ISSUE TITLE
Kill a running script

### ISSUE THREAD

**Issue by jowanw** [rannn505/node-powershell#76]
Is it possible to kill a running script?

In my situation i have a new shell at the top of the script which is used forever. I have a long running script that i might need to cancel in the middle.

When i use .dispose it doesnt stop the running script, but waits until its completed. Also since i used dispose i need to restart the app to start running commands again.

**Comment by BenjaminMichael** [comment]
Yes and no.  There is always a way to write a PowerShell script so that it is in a While loop always checking to see if the user has cancelled the script.

Also yes, Node could kill the process on demand.  You PS script could also do this with jobs.  Your jobs could also time out in a PS script.

But no, what you are asking for does not sound possible with Node-PowerShell today.  If you describe your use case in more detail maybe this process killing method could be added.  It sounds simple I'm just not convinced its needed or would even give reliable results depending on what processes were in the middle of doing when you killed them.

Here an example of a script block with a basic timeout:

```powershell
$Job = Start-Job -ScriptBlock {

    Invoke-Command -ComputerName localhost -ScriptBlock {
    #
        Get-ChildItem c:\scripts\*.* -Recurse | select name | Out-File 'C:\Scripts\myfile.txt'
    #
    } 


}

$Job | Wait-Job -Timeout 10
$Job | Stop-Job

```
Another common scenario is a web listener waiting for an http request that may or may not becoming and we dont know when

```powershell
# enter this URL to reach PowerShell’s web server
$url = 'http://localhost:8080/'

# HTML content for some URLs entered by the user
$htmlcontents = @{
  'GET /'  =  '<html><building>Here is PowerShell</building></html>'
  'GET /services'  =  Get-Service | ConvertTo-Html

}

# start web server
$listener = New-Object System.Net.HttpListener
$listener.Prefixes.Add($url)
$listener.Start()

try
{
  while ($listener.IsListening) {  
    # process received request
    $context = $listener.GetContext()
    $Request = $context.Request
    $Response = $context.Response

    $received = '{0} {1}' -f $Request.httpmethod, $Request.url.localpath
    
    # is there HTML content for this URL?
    $html = $htmlcontents[$received]
    if ($html -eq $null) {
      $Response.statuscode = 404
      $html = 'Oops, the page is not available!'
    } 
    
    # return the HTML to the caller
    $buffer = [Text.Encoding]::UTF8.GetBytes($html)
    $Response.ContentLength64 = $buffer.length
    $Response.OutputStream.Write($buffer, 0, $buffer.length)
    
    $Response.Close()
  }
}
finally
{
  $listener.Stop()
}
```

**Comment by Vijay-Nirmal** [comment]
@jowanw In my case, I am starting a web server (dotnet run) from PowerShell at the start of the application. I need to end it at the "window-all-closed" event. How do I do it? If I call dispose then the webserver is still running.

**Comment by Wizek** [comment]
I also need this. Perhaps it's better to use https://nodejs.org/api/child_process.html than node-powershell? As that API does have a `.kill()` command.
